# Generated by Django 5.0.2 on 2024-03-05 16:56

import utils.db.model_helper
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_customuser_managers_alter_customuser_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otp",
            name="otp",
            field=models.CharField(
                default=utils.db.model_helper.generate_otp, max_length=6
            ),
        ),
    ]
