# Generated by Django 5.0.2 on 2024-03-05 21:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_otp_otp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="phone",
            field=models.CharField(
                max_length=11,
                validators=[
                    django.core.validators.RegexValidator(
                        message="The phone number is wrong. The phone number must be 11 digits and start with 09",
                        regex="^09\\d{9}$",
                    )
                ],
            ),
        ),
    ]
