# Generated by Django 5.0.2 on 2024-03-05 23:04

import utils.db.model_helper
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_customuser_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile_image",
            field=models.ImageField(
                blank=True, null=True, upload_to=utils.db.model_helper.user_image_path
            ),
        ),
    ]
