# Generated by Django 5.0.2 on 2024-03-06 08:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import utils


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_customuser_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="email address"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone",
            field=models.CharField(
                max_length=11,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="The phone number is wrong. The phone number must be 11 digits and start with 09",
                        regex="^09\\d{9}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="users.team",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="profile_image",
            field=models.ImageField(
                blank=True, null=True, upload_to=utils.db.model_helper.user_image_path
            ),
        ),
    ]
