# Generated by Django 4.2.11 on 2024-03-07 16:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_customuser_first_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "permissions": [
                    ("add_reservation_self_team", "Can add reservation to their team"),
                    (
                        "change_reservation_self_team",
                        "Can change reservation of their team",
                    ),
                    (
                        "delete_reservation_self_team",
                        "Can delete reservation of their team",
                    ),
                    ("view_room_list", "Can view rooms list"),
                    ("view_reservation_list", "Can view reservations list"),
                    ("view_customuser_list", "Can view users list"),
                    ("view_team_list", "Can view teams list"),
                ]
            },
        ),
    ]
