# Generated by Django 4.2.11 on 2024-03-07 19:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_alter_customuser_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "permissions": [
                    ("add_reservation_self_team", "Can add reservation to their team"),
                    (
                        "delete_reservation_self_team",
                        "Can delete reservation of their team",
                    ),
                ]
            },
        ),
    ]
