# Generated by Django 4.2.11 on 2024-03-09 12:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_alter_customuser_team"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
    ]
