# Generated by Django 5.0.2 on 2024-03-05 21:10

import datetime
import django.core.validators
from django.db import migrations, models


def set_default_date(apps, schema_editor):
    Reservation = apps.get_model("reservation", "Reservation")
    for reservation in Reservation.objects.all():
        if not reservation.start_date:
            reservation.start_date = datetime.datetime.now()
            reservation.end_date = reservation.start_date + datetime.timedelta(hours=1)
            reservation.save()


class Migration(migrations.Migration):
    dependencies = [
        ("reservation", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reservation",
            old_name="user",
            new_name="reserver_user",
        ),
        migrations.RenameField(
            model_name="room",
            old_name="status",
            new_name="is_active",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="date",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="time",
        ),
        migrations.AddField(
            model_name="reservation",
            name="end_date",
            field=models.DateTimeField(),
        ),
        migrations.AddField(
            model_name="reservation",
            name="start_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="rating",
            name="value",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ]
            ),
        ),
        migrations.RunPython(set_default_date),
    ]
