# Generated by Django 5.0.2 on 2024-03-05 21:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservation", "0003_rename_user_reservation_reserver_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="capacity",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
