# Generated by Django 4.2.11 on 2024-03-06 11:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservation", "0004_alter_room_capacity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="value",
            field=models.SmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ]
            ),
        ),
    ]
