# Generated by Django 4.2.11 on 2024-03-09 12:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reservation", "0005_alter_rating_value"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reservation",
            options={
                "permissions": [
                    ("add_reservation_self_team", "Can add reservation to their team"),
                    (
                        "delete_reservation_self_team",
                        "Can delete reservation of their team",
                    ),
                ]
            },
        ),
    ]
